### PR TITLE
Adjust default language for ancestries to match Starfinder

### LINKED ISSUE #99: Ancestries default language should be Pact Worlds Common instead of regular Common
Title says it all, since we're using the pf2e system as a base, common gets defaulted to Taldane while it should be Pact Worlds Common for Starfinder Ancestries.

### PR DESCRIPTION
**Pull request by jesuisfrog**
Closes #99

### CODE REVIEW

**Comment by CarlosFdez** [comment]
common isn't actually a language in the pathfinder system, but a placeholder language that turns into a real language. By default that language would be Taldane, but in some campaigns its Tian. This needs to be preserved because of homebrew settings or potential specific campaigns.

The correct fix would be to support overriding the default language in a module, but that needs to be done in the PF2e system itself.

**Comment by jesuisfrog** [comment]
For the sake of the playtest module, wouldn't it be better to default to Pact Worlds Common ?

Starfinder's common is more.. well.. common than Pathfinder's since it's not region based.

**Comment by CarlosFdez** [comment]
The difference is the context. "common" in the character means "the common language of the campaign". The configured common language in the settings changes "the common language of the campaign". Changing the common language in the settings updates it for all characters. We lose the ability for players to mass-update the common language (as well as all compatibility, an intent of the sf2e playtest) if we change the ancestry languages.

We need the pf2e system to allow changing this default, but there's a lot of bigger fish to fry (dammit pc2). It might be wise to include this as a step in the readme in the meantime.

image

**Comment by jesuisfrog** [comment]
Fair point, I'll close this then.

**Pull request closed without merging**
